### ISSUE TITLE
Submit the paper to bioRxiv (or Zenodo) as a preprint before or at the same time as uploading to Nutrients

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/legliv#19]
As per the purpose of the Steno UK Biobank project, we want our output to be put in archives as preprints.

**Comment by lwjohnst86** [comment]
@nielsbock just to confirm, I should upload the `report.Rmd` file right?

**Comment by lwjohnst86** [comment]
Or rather, the pdf. What about the supplemental file?

**Comment by lwjohnst86** [comment]
And what about the supplemental text? I see it in the `report.Rmd` but not in the pdf. It needs to be regenerated I assume?

**Comment by nielsbock** [comment]
It's the `report.pdf`, yes. Supplemental tables and figure are in the pdf, just before references. I couldn't find a pandoc template putting supplemental materials after references.

**Comment by nielsbock** [comment]
@lwjohnst86 `targets::tar_make()` will now prepare all code needed to compile `report.Rmd`!

**Comment by lwjohnst86** [comment]
Preprint is up! https://zenodo.org/records/12666778 DOI: https://doi.org/10.5281/zenodo.12666778
