### ISSUE TITLE
After (or during?) submission, create a GitHub release and connect it to Zenodo

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/legliv#27]
So that a DOI can be created. After review, maybe the DOI can be included then. Or should it be included before submission...? I'm not sure.

**Comment by nielsbock** [comment]
I've made some minor changes to the code after the zenodo upload. Should it be reuploaded?

**Comment by lwjohnst86** [comment]
Done! Uploaded the latest version
